# Generated by Django 5.1.5 on 2025-02-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=255)),
                ('time_available_from', models.TimeField()),
                ('time_available_till', models.TimeField()),
                ('campus_side', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('Central', 'Central'), ('N/A', 'N/A')], max_length=10)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
